config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts

  # TODO: Add root route as needed/necessary
  # unauthenticated :user do
  #   root to: 'static_pages#landing'
  # end
  
  get 'uploads', to: 'uploads#index'
  post 'upload', to: 'uploads#upload'
  resources :properties do 
    resources :tenants, only: :show
  end
  root to: 'properties#index'
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  belongs_to :authenticatable, polymorphic: true

  private

  # Deliver Devise emails asynchronously.
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/importable.rb
require 'csv'

module Importable
  extend ActiveSupport::Concern

  included do
    def self.import_data(file)
      klass = self.name
      data = data_builder(file, klass)

      case klass
      when "Property"
        Property.upsert_all(data, unique_by: :external_id)
      when "Tenant"
        Tenant.upsert_all(data, unique_by: :external_id)
      end
    end
  end

  class_methods do
    def data_builder(file, model)
      data = []
      CSV.foreach(file.path, headers: true) do |row|
        data << if model.eql?('Property') 
          property_data(row) 
        else
          property = Property.find_by(external_id: row[2])
          next if property.blank?
          tenant_data(row, property)
        end
      end
      data
    end

    private

    def property_data(row)
      {
        name:          row[0],
        external_id:   row[1],
        property_type: row[2],
        city:          row[3],
        country:       row[4],
        price:         row[5],
        leasable_area: row[6],
        acquired_on:   DateTime.strptime(row[7], '%m/%d/%Y'),
      }
    end

    def tenant_data(row, property)
      {
        name:          row[0],
        external_id:   row[1],
        property_id:   property.id,
        tenant_type:   row[3],
        floor:         row[4],
        leasable_area: row[5],
        lease_commenced_on: DateTime.strptime(row[6], '%m/%d/%Y'),
        base_rent:     row[7],
      }
    end
  end
end

app/models/property.rb
class Property < ApplicationRecord
  include Importable
  has_many :tenants, dependent: :destroy
  validates :external_id, uniqueness: true, presence: true
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  include Importable
  belongs_to :property
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  helper_method :current_user

  protect_from_forgery with: :exception
  rescue_from ActionController::InvalidAuthenticityToken do
    flash[:alert] = I18n.t('app.authenticity_token_expired')
    redirect_back fallback_location: root_path, allow_other_host: false
  end

  before_action :authenticate_account!
  before_action :set_sentry_user

  private

  # A shorthand for passing locals to views, avoiding implicitly passed instance
  # variables.
  #
  # The following calls are equivalent to each other:
  #   render action: :new, locals: { the_anser: 42 }
  #   expose :new, the_answer: 42
  #
  #   render locals: { the_anser: 42 }
  #   expose the_anser: 42
  #
  # @param action [Symbol] action to render, only necessary if not default
  # @param locals [Hash<Symbol, Object>] locals to be passed to the view
  # @return [void]
  def expose(action = nil, **locals)
    render action: action, locals: locals
  end

  def current_user
    @current_user ||= current_account&.authenticatable
  end

  def set_sentry_user
    Sentry.set_user(id: current_user&.id)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  skip_before_action :authenticate_account!
  skip_before_action :set_sentry_user

  before_action :property, only: [:show]

  def index
    @properties = PropertyDecorator.decorate_collection(Property.all)
  end

  def show
  end

  private

  def property
    @property ||= Property.find(params[:id])
    @property_decorated ||= PropertyDecorator.new(@property)
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  skip_before_action :authenticate_account!
  skip_before_action :set_sentry_user

  before_action :tenant, only: [:show]

  def show
  end

  private

  def tenant
    @tenant ||= Tenant.find(params[:id])
    @tenant_decorate ||= TenantDecorator.new(@tenant)
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  skip_before_action :authenticate_account!
  skip_before_action :set_sentry_user

  def index
  end

  def upload
    prop = params[:prop]
    tenn = params[:tenn]

    if prop.present?
      Property.import_data(prop)
    end

    if tenn.present?
      Tenant.import_data(tenn)
    end

    redirect_to properties_url, notice: "Data Imported"
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # Translate Rails standard flash keys for Bootstrap
  def flash_alert_class(name)
    case name
    when 'notice' then 'alert-success'
    when 'alert'  then 'alert-danger'
    else name
    end
  end
end

app/views/layouts/_favicon.html.erb
<link rel="shortcut icon" href="/favicon.ico">

<% %w(36 48 72 96 144 192).each do |size| %>
    <link href="<%= "/android-chrome-#{size}x#{size}.png" %>"
          rel="icon"
          type="image/png"
          sizes="<%= "#{size}x#{size}" %>" />
<% end %>

<% %w(57 60 72 76 114 120 144 152 180).each do |size| %>
    <link href="<%= "/apple-touch-icon-#{size}x#{size}.png" %>"
          rel="apple-touch-icon"
          type="image/png"
          sizes="<%= "#{size}x#{size}" %>" />
<% end %>
<link content="apple-touch-icon-precomposed.png"
      rel="apple-touch-icon-precomposed" />

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <div class="row-fluid alerts">
    <% flash.each do |name, message| %>
      <div class="alert alert-dismissible <%= flash_alert_class(name) %> fade show" role="alert">
        <div class="container">
          <button class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_google_analytics.html.erb
<% if ENV['GOOGLE_ANALYTICS_ID'].present? %>
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script>
  SETTINGS.google_analytics_id = "<%= ENV['GOOGLE_ANALYTICS_ID'] %>"
</script>
<script async src="<%= "https://www.googletagmanager.com/gtag/js?id=#{ENV['GOOGLE_ANALYTICS_ID']}" %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());
</script>
<% end %>

app/views/layouts/_js_setup.html.erb
<script>
  var SETTINGS = {
    // Errors are only reported to Sentry if the token is set.
    SENTRY_DSN_FRONTEND: "<%= ENV['SENTRY_DSN_FRONTEND'] %>"
  };
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>

    <title><%= yield(:page_title).presence || t('app.default_title') %></title>

    <%= render partial: 'layouts/js_setup' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render partial: 'layouts/google_analytics' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
    <%= render partial: 'layouts/favicon' %>
    <link rel='manifest' href='/manifest.json'>
  </head>

  <body class="bg-light">
    <%= render partial: 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/properties/_details.html.erb
<ul class="list-group mb-3">
  <li class="mb-3 d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">
        <b>Name:</b> 
        <%= @property_decorated.wrapped.name %></h6>
    </div>
  </li>
  <li class="mb-3 d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">
        <b>External ID:</b> 
        <%= @property_decorated.wrapped.external_id %></h6>
    </div>
  </li>
  <li class="mb-3 d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">
        <b>Property Type:</b> 
        <%= @property_decorated.wrapped.property_type %></h6>
    </div>
  </li>
  <li class="mb-3 d-flex justify-content-between bg-light">
    <div>
      <h6 class="my-0">
        <b>City:</b> 
        <%= @property_decorated.wrapped.city %></h6>
    </div>
  </li>
  <li class="mb-3 d-flex justify-content-between bg-light">
    <div>
      <h6 class="my-0">
        <b>Country:</b> 
        <%= @property_decorated.wrapped.country %></h6>
    </div>
  </li>
  <li class="mb-3 d-flex justify-content-between bg-light">
    <div>
      <h6 class="my-0">
        <b>Acquisition Price:</b> 
        <%= @property_decorated.acquisition_price %></h6>
    </div>
  </li>
  <li class="mb-3 d-flex justify-content-between bg-light">
    <div>
      <h6 class="my-0">
        <b>Leasable area:</b> 
        <%= @property_decorated.leasable_area %></h6>
    </div>
  </li>
  <li class="mb-3 d-flex justify-content-between bg-light">
    <div>
      <h6 class="my-0">
        <b>Acquired on:</b> 
        <%= @property_decorated.acquired_on %></h6>
    </div>
  </li>
</ul>
<ul class="list-group mb-3">
  <li class="mb-3 d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">
        <b>Leased area:</b> 
        <%= @property_decorated.leased_area %></h6>
    </div>
  </li>
  <li class="mb-3 d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">
        <b>Occupancy rate:</b> 
        <%= @property_decorated.occupancy_rate%></h6>
    </div>
  </li>
  <li class="mb-3 d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">
        <b>Total monthly rent:
        </b> <%= @property_decorated.total_monthly_rent %></h6>
    </div>
  </li>
</ul>

app/views/properties/index.html.erb
<div class="container">
  <div class="py-5 text-center">
    <img class="d-block mx-auto mb-4" src="https://avatars.githubusercontent.com/u/1837470" alt="" width="72" height="72">
    <%= link_to "Upload Data", uploads_path, class: "btn btn-primary"%>
    <p class="lead"></p>
  </div>

  <div class="row">
    <div class="col-md-2 order-md-1 mb-4"></div>
    <div class="col-md-8 order-md-2">
      <h4 class="mb-3">Properties</h4>
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Country</th>
            <th scope="col">Monthly rent</th>
          </tr>
        </thead>
        <tbody>
          <% if @properties.blank? %>
            <tr>
              <td colspan="3" class="text-center"><p>There is no data</p></td>
            </tr>
          <% else %>
            <% @properties.each do |p| %>
              <tr>
                <td><%= link_to p.wrapped.name, property_path(p.wrapped.id) %></td>
                <td><%= p.wrapped.country  %></td>
                <td><%= p.monthly_rent %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-2 order-md-3 mb-4"></div>
  </div>
</div>

app/views/properties/show.html.erb
<div class="container">
  <div class="py-5 text-center">
    <img class="d-block mx-auto mb-4" src="https://avatars.githubusercontent.com/u/1837470" alt="" width="72" height="72">
    <%= link_to "Go to Properties", properties_path, class: "btn btn-primary"%>
    <p class="lead"></p>
  </div>

  <div class="row">
    <div class="col-md-2 order-md-1 mb-4"></div>
    <div class="col-md-8 order-md-2">
      <h4 class="mb-3"><%= @property_decorated.wrapped.name %></h4>
      <%= render partial: 'properties/details' %>
    </div>
    <div class="col-md-2 order-md-3 mb-4"></div>
  </div>

  <div class="row">
    <div class="col-md-2 order-md-1 mb-4"></div>
    <div class="col-md-8 order-md-2">
      <%= render partial: 'tenants/list', locals: {
        property: @property, 
        tenants: TenantDecorator.decorate_collection(@property_decorated.wrapped.tenants)
      } %>
    </div>
    <div class="col-md-2 order-md-3 mb-4"></div>
  </div>
</div>

app/views/tenants/_details.html.erb
<ul class="list-group mb-3">
  <li class="mb-3 d-flex justify-content-between lh-condensed">
    <div>
      <h6 class="my-0">
        <b>Name:</b> <%= 
        @tenant_decorate.wrapped.name %></h6>
      </div>
    </li>
    <li class="mb-3 d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">
          <b>External ID:</b> 
          <%= @tenant_decorate.wrapped.external_id %></h6>
        </div>
      </li>
      <li class="mb-3 d-flex justify-content-between lh-condensed">
        <div>
          <!-- TODO: Use Deligate -->
          <h6 class="my-0">
            <b>Property ID:</b> 
            <%= @tenant_decorate.wrapped.property.external_id %></h6>
          </div>
        </li>
        <li class="mb-3 d-flex justify-content-between bg-light">
          <div>
            <h6 class="my-0">
              <b>Tenant Type:</b> 
              <%= @tenant_decorate.wrapped.tenant_type %></h6>
            </div>
          </li>
          <li class="mb-3 d-flex justify-content-between bg-light">
            <div>
              <h6 class="my-0">
                <b>Floor:</b> <%= 
                @tenant_decorate.wrapped.floor %></h6>
              </div>
            </li>
            <li class="mb-3 d-flex justify-content-between bg-light">
              <div>
                <h6 class="my-0">
                  <b>Leasable area:</b> 
                  <%= @tenant_decorate.leasable_area %></h6>
                </div>
              </li>
              <li class="mb-3 d-flex justify-content-between bg-light">
                <div>
                  <h6 class="my-0">
                    <b>Lease commenced on:</b>
                    <%= @tenant_decorate.lease_commenced_on %></h6>
                  </div>
                </li>
                <li class="mb-3 d-flex justify-content-between bg-light">
                  <div>
                    <h6 class="my-0">
                      <b>Base rent:</b> 
                      <%= @tenant_decorate.base_rent %></h6>
                    </div>
                  </li>
                </ul>

app/views/tenants/_list.html.erb
<h5 class="mb-3">Tenants</h5>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Floor</th>
      <th scope="col">Monthly rent</th>
    </tr>
  </thead>
  <tbody>
    <% if tenants.blank? %>
    <tr>
      <td colspan="3" class="text-center"><p>There is no data</p></td>
    </tr>
    <% else %>
    <% tenants.each do |t| %>
    <tr>
      <td><%= link_to t.wrapped.name, property_tenant_path(property.id, t.wrapped.id) %></td>
      <td><%= t.wrapped.floor  %></td>
      <td><%= t.base_rent %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/tenants/show.html.erb
<div class="container">
  <div class="py-5 text-center">
    <img class="d-block mx-auto mb-4" src="https://avatars.githubusercontent.com/u/1837470" alt="" width="72" height="72">
    <%= link_to "Go back to #{@tenant_decorate.wrapped.property.name}", property_path(@tenant_decorate.wrapped.property), class: "btn btn-primary"%>
    <p class="lead"></p>
  </div>

  <div class="row">
    <div class="col-md-2 order-md-1 mb-4"></div>
    <div class="col-md-8 order-md-2">
      <h4 class="mb-3"><%= @tenant_decorate.wrapped.name %></h4>
      <%= render partial: 'tenants/details' %>
    </div>
    <div class="col-md-2 order-md-3 mb-4"></div>
  </div>
</div>

app/views/uploads/index.html.erb
<div class="container">
  <div class="py-5 text-center">
    <img class="d-block mx-auto mb-4" src="https://avatars.githubusercontent.com/u/1837470" alt="" width="72" height="72">
    <%= link_to "Go to Properties", properties_path, class: "btn btn-primary"%>
    <p class="lead"></p>
  </div>

  <div class="row">
    <div class="col-md-2 order-md-1 mb-4"></div>
    <div class="col-md-8 order-md-2">
      <h4 class="mb-3">Data upload</h4>
      <%= form_with url: "/upload", method: :post do |f| %>
        <div class="row">
          <div class="col-md-8 mb-3 order-md-1">
            <%= f.label :prop, "Properties", class: "col-2 p-0" %>
            <%= f.file_field :prop, class: "col-6", required: true %>
          </div>
          <div class="col-4 order-md-2">
            <%= f.submit "Upload", class: "btn btn-primary" %>
          </div>  
        </div>
      <% end %>
      <%= form_with url: "/upload", method: :post do |f| %>
        <div class="row">
          <div class="col-md-8 mb-3 order-md-1">
            <%= f.label :tenn, "Tenants", class: "col-2 p-0" %>
            <%= f.file_field :tenn, class: "col-6", required: true %>
          </div>
          <div class="col-4 order-md-2">
            <%= f.submit "Upload", class: "btn btn-primary" %>
          </div>  
        </div>
      <% end %>
    </div>
    <div class="col-md-2 order-md-3 mb-4"></div>
  </div>
</div>